apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vitals-app
  namespace: argocd
  annotations:
    # Enable Git Write-Back method
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    
    # Configure image watch list and tracking strategy (SemVer constraints)
    argocd-image-updater.argoproj.io/image-list: backend=vitals-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/backend.allow-tags: ~1.16.x
spec:
  project: default
  source:
    repoURL: 'git://git-server.vitals-app.svc.cluster.local:9418/gitops-galaxy.git'
    targetRevision: main
    path: charts/vitals-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vitals-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
