apiVersion: v1
kind: ResourceQuota
metadata:
  name: vitals-quota
  namespace: vitals-app
spec:
  hard:
    pods: "15"
    requests.cpu: "1500m"
    requests.memory: "1500Mi"
    limits.cpu: "3"
    limits.memory: "3Gi"
