apiVersion: v1
kind: ConfigMap
metadata:
  name: vitals-config
  namespace: {{ .Values.namespace }}
data:
  BACKEND_URL: {{ .Values.frontend.config.backendUrl | quote }}
  PORT: {{ .Values.frontend.service.port | quote }}
